name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Upload-File:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ./artifact
      - run: echo hello > ./artifact/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./artifact/world.txt
      

  # Upload-Artifact:
  #   steps:
  #     - run: mkdir -p path/to/artifact
  #     - run: echo hello > path/to/artifact/world.txt
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: my-artifact
  #         path: path/to/artifact/world.txt


