name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Create-File:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      

  # Upload-Artifact:
  #   steps:
  #     - run: mkdir -p path/to/artifact
  #     - run: echo hello > path/to/artifact/world.txt
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: my-artifact
  #         path: path/to/artifact/world.txt


