name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Download-File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact-v1
      - name: Display structure of downloaded files
        run: ls -R
      - run: cat world.txt
    
  # Upload-File:
  #   runs-on: ubuntu-latest
  #   steps:
  #       # - uses: actions/checkout@v4
  #       #   with:
  #       #     sparse-checkout: |
  #       #       create_file.sh
  #       #     sparse-checkout-cone-mode: false
  #       # - run: chmod +x create_file.sh
  #       # - run: ./create_file.sh
  #       - run: echo hello > world.txt
  #       - uses: actions/upload-artifact@v4
  #         with:
  #           name: my-artifact-v1
  #           path: world.txt


